---
title: "Air Traffic Challenge"
output: 
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: true 
    number_sections: true 
    df_print: paged
---


__Team Airtraffic has created insightful visualizations of air traffic from / to Zurich Airport and built farly acurate delay prediction models__


At the TWIST-Hackdays, the *terrific* __Team Airtraffic__ has: 

- conducted __exploratory data analysis__ and produced many descriptive visualizations to get to know the data and get a first understanding of which aspects of it might be relevant and interesting
- experimented with a broad variety of modelling approaches (linear approaches, binary logistic regressions, ridge regression, baynesian approaches) __to predict delays__
-the fitted models predicted delays on the test data with a high accuracy


# What We've achieved!

[1. Explorative Data Analysis](https://openzh.github.io/twist_airtraffic/airtraffic_prediction)

[2. Flight Delay Predictions (linear, logistic, bayesian)](https://openzh.github.io/twist_airtraffic/airtraffic_prediction)

[3. Flight Delay Predictions (gam)](https://openzh.github.io/twist_airtraffic/gam)

[4. Geogiffery!](https://openzh.github.io/twist_airtraffic/animated_flights)

[5. A bit of analysis related to nightflights](https://github.com/openZH/twist_airtraffic/blob/master/docs/nightflights.png)

# What we could have done (with a bit more time)

A (shiny) prototype of a __flight prediction app__ based on the best prediction models! 








